# for runtime: nvidia
version: '2.3'
services:
    myapp:
        runtime: nvidia
        container_name: keras
        build:
            context: .
        volumes:
            - ./:/usr/app
        ports:
            - "24375:8888"
        working_dir: /usr/app
        tty: true
